language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install phantomjs
- npm install -g karma
- bower install
before_deploy:
- grunt build
deploy:
  provider: heroku
  app: hackbox
  on:
    repo: JaggedCloud/JaggedCloud
  api_key:
    secure: gk8ZNrOBxVGWzqsjfw3MK4ClxAixjqS32iju3kWR5+8flq1K/suff7EloqvbO6Ye4nb9WQerc0Y9vl7JObUjEakL4uxcFnaHufslss9qn6VO6NuLvpe3+6iKkM8QFRGlh9OraSvoNCsJ+GyUIlSkYe8nhOmwm8qEuUuWfC7Vq28=
