language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install phantomjs
- npm install -g karma
- bower install
deploy:
  provider: heroku
  api_key:
    secure: Emjjf/8QGdpVs6AgHBcYHvoaHW2HdNR6wnZcLrkMWN9uNDS9QYfg7sOUjqIvgN6Ja7e7BlNFCQwYauVC8SErVCeT8Wzz7j94ZQnvhZGlOxA78Jm/uUYqBkAXvDLW8/7e4uUN44sn1OlBoQqNy3ZXkCxfH9Xt+cydPh+RIFtXAYA=
  app: hackbox
  on:
    repo: JaggedCloud/JaggedCloud
