language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g bower
- npm install phantomjs
- npm install -g karma
- bower install
deploy:
  provider: heroku
  api_key:
    secure: UR0JICmjtflCyXQ9NNCGf4C0PmtDv3j0LEEIE+pXKgo1KFFZcorcHxgMaDQpStrdF/abNIG32P/rzs1myCO9xBH5NiZ1lJhrGbE5te0c0iWxqiMFnSuyDR+UhVhNByJ2KXS/QKFsyRi6vLpfJqtS4q5UQlsMNspQIbDAZWjjnCA=
  app: hackbox
  on:
    repo: JaggedCloud/JaggedCloud